import FilterContainer from "@/components/FilterContainer";
import Navbar from "@/components/Navbar";
import "./globals.css";
import SectionProvider from "./SectionProvider";

export const metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SectionProvider>
          <Navbar />
          <FilterContainer />
          {children}
        </SectionProvider>
      </body>
    </html>
  );
}
