import FilterContainer from "@/components/FilterContainer";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import SectionProvider from "./SectionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SectionProvider>
          <Navbar />
          <FilterContainer />
          <main className={inter.className}>{children}</main>
        </SectionProvider>
      </body>
    </html>
  );
}
